AllCops:
  Exclude:
    - 'bin/console'

  NewCops: enable

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
