AllCops:
  NewCops: enable
  Exclude:
    - 'bin/console'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'tasks/*.rake'
    - 'lib/aspire_budget/models/*.rb' # TODO: refactor and enable
