env:
  RUBY_VERSION: 2.7.1
  ENABLE_CODE_COVERAGE: 1

name: build-test
on: push
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop
  rspec-test:
    name: RSpec
    needs: rubocop-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Run tests
        run: bundler exec rspec
      - name: Upload resultset artifact
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
  upload-codecov:
    name: Codecov
    needs: rspec-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Download resultset artifact
        uses: actions/download-artifact@v1
        with:
          name: coverage-report
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage-report/.resultset.json
